EXP_NAME: Train_D_G_w100_step1_hid100

MODE:
  Train_model: True
  Optimize: True

SEED: 1998

save_dir: ./saved_models

DATASET:
  window_size: 100
  hidden_dim: 100
  step_size: 1
  in_dim: 1
  scaler: standard
  data_dir: ./NAB/data/realKnownCause/nyc_taxi.csv
  label_dir: ./NAB/labels/combined_windows.json
  TRAIN_RATIO: 0.7
  VAL_RATIO: 0.1
  batch_size: 32

TRAIN:
  lr: 0.0001
  epochs: 20
  log_interval: 1
  eval_interval: 10
  use_wandb: True

Saved_models:
  gen_dir: gen_best_model.pt
  dis_dir: dis_best_model.pt
  lastascheckpoint: False
  last_gen_dir: gen_last_model.pt
  last_dis_dir: dis_last_model.pt

Optimize:
  lambda: 0.1
  iterations: 50
