wandb_version: 1

DATASET:
  desc: null
  value:
    batch_size: 256
    input_dir: ./data/TimeSeries.csv
    label_dir: ./data/labelsTimeSeries.csv
    num_workers: 12
    preprocess: true
    slide_size: 1
    split_ratio:
    - 0.6
    - 0.1
    - 0.3
    window_size: 1
LOG:
  desc: null
  value:
    eval_interval: 10
    log_interval: 1
MODEL:
  desc: null
  value:
    dropout: 0.2
    hidden_dim: 10
    input_dim: 11
    latent_dim: 1
    n_gmm: 5
TRAIN:
  desc: null
  value:
    SEED: 1998
    epochs: 10
    lambda1: 0.001
    lambda2: 0.005
    lr: 0.0001
    use_wandb: true
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    start_time: 1676806558.727439
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.6.10
      5: 0.13.10
      8:
      - 5
exp_name:
  desc: null
  value: TS-MTSAD
save_dir:
  desc: null
  value: ./save_models/
