wandb_version: 1

DATASET:
  desc: null
  value:
    TRAIN_RATIO: 0.7
    VAL_RATIO: 0.1
    batch_size: 32
    data_dir: ./NAB/data/realKnownCause/ambient_temperature_system_failure.csv
    hidden_dim: 100
    in_dim: 1
    label_dir: ./NAB/labels/combined_windows.json
    scaler: standard
    split: true
    step_size: 1
    window_size: 60
EXP_NAME:
  desc: null
  value: Train_D_G_w60_step1_hid100
MODE:
  desc: null
  value:
    Optimize: true
    Train_model: true
Optimize:
  desc: null
  value:
    iterations: 50
    lambda: 0.1
SEED:
  desc: null
  value: 2
Saved_models:
  desc: null
  value:
    dis_dir: dis_best_model.pt
    gen_dir: gen_best_model.pt
    last_dis_dir: dis_last_model.pt
    last_gen_dir: gen_last_model.pt
    lastascheckpoint: false
TRAIN:
  desc: null
  value:
    epochs: 20
    eval_interval: 10
    log_interval: 1
    lr: 0.0002
    use_wandb: true
_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1677722401.350615
    t:
      1:
      - 1
      - 51
      - 55
      2:
      - 1
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.13.10
      8:
      - 5
save_dir:
  desc: null
  value: ./saved_models
